<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\config.props" />

    <PropertyGroup>
        <PackageId>TnmsLocalizationPlatform.Shared</PackageId>
        <AssemblyName>TnmsLocalizationPlatform.Shared</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.121" ExcludeAssets="runtime" />
    </ItemGroup>

</Project>
