<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\config.props" />

    <PropertyGroup>
        <AssemblyName>TnmsLocalizationPlatform</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="TnmsDatabaseUtil.Shared" Version="0.0.4" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.121" ExcludeAssets="runtime" />
        <ProjectReference Include="..\TnmsLocalizationPlatform.Shared\TnmsLocalizationPlatform.Shared.csproj" Private="false" />
    </ItemGroup>

</Project>
